export const GET_LECTURES = 'GET_LECTURES'
export const GET_LECTURES_SUCCESS = 'GET_LECTURES_SUCCESS'

export const GET_ASSIGNMENTS = 'GET_ASSIGNMENTS'
export const GET_ASSIGNMENTS_SUCCESS = 'GET_ASSIGNMENTS_SUCCESS'

export const GET_SIGNLE_ASSIGNMENT = 'GET_SIGNLE_ASSIGNMENT'
export const GET_SIGNLE_ASSIGNMENT_SUCCESS = 'GET_SIGNLE_ASSIGNMENT_SUCCESS'
