export const GET_LECTURES = 'GET_LECTURES'
export const GET_LECTURES_SUCCESS = 'GET_LECTURES_SUCCESS'

export const GET_LECTURE_GROUPS = 'GET_LECTURE_GROUPS'
export const GET_LECTURE_GROUPS_SUCCESS = 'GET_LECTURE_GROUPS_SUCCESS'

export const GET_LECTURE_GROUP = 'GET_LECTURE_GROUP'
export const GET_LECTURE_GROUP_SUCCESS = 'GET_LECTURE_GROUP_SUCCESS'

export const GET_ASSIGNMENTS = 'GET_ASSIGNMENTS'
export const GET_ASSIGNMENTS_SUCCESS = 'GET_ASSIGNMENTS_SUCCESS'

export const GET_SIGNLE_ASSIGNMENT = 'GET_SIGNLE_ASSIGNMENT'
export const GET_SIGNLE_ASSIGNMENT_SUCCESS = 'GET_SIGNLE_ASSIGNMENT_SUCCESS'

export const SUBMIT_SOLUTION = 'SUBMIT_SOLUTION'
export const SUBMIT_SOLUTION_SUCCESS = 'SUBMIT_SOLUTION_SUCCESS'

export const OPEN_TOAST = 'OPEN_TOAST'
export const CLOSE_TOAST = 'CLOSE_TOAST'

export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const UNAUTHORIZED_ACTION = 'UNAUTHORIZED_ACTION'
